---
  notifications:
    email: false

  matrix:
    include:
      - language: go
        go: 1.9.x
        env: TESTFILE=unit.sh
      - language: go
        go: 1.10.x
        env: TESTFILE=unit.sh
      - language: go
        go: master
        env: TESTFILE=unit.sh
      - language: generic
        sudo: required
        services:
          - docker
        before_install:
          - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          - sudo apt-get update
          - sudo apt-get -y install docker-ce
        env: TESTFILE=integration.sh

  script:
    - ./.travis/$TESTFILE